---

name: Build tpnode

on:
  push:
     branches:
       - github_actions

env:
  GIT_DISCOVERY_ACROSS_FILESYSTEM: true

permissions:
  contents: read

jobs:

  build_tpnode:

    runs-on: self-hosted

    container:
      image: ubuntu:22.04

    steps:
    - name: Update
      run: apt-get update -yqq

    - name: Install soft
      run: apt-get install -yqq cmake clang gcc git curl libssl-dev
           build-essential automake autoconf libncurses5-dev elixir
           erlang-base erlang-public-key erlang-asn1 erlang-ssl
           erlang-dev erlang-inets erlang-eunit erlang-common-test
           rebar3 iputils-ping

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-tags: true
        fetch-depth: 2

    - name: Debug
      run: |
        pwd
        ls -al

    - name: Git describe
      run: git describe

    - name: Compile tpnode
      run: DIAGNOSTIC=1 rebar3 compile

    - name: Release tpnode
      run: rebar3 release

    - name: Tar tpnode
      run: rebar3 tar

...
