name: Build tpnode

on:
  push:
     branches:
       - github_actions

permissions:
  contents: read

jobs:

  build_tpnode:

    runs-on: self-hosted

    container:
      image: ubuntu:22.04

    steps:

    - name: Update
      run: apt-get update -yqq

    - name: Install soft
      run: apt-get install -yqq cmake clang gcc git curl libssl-dev
           build-essential automake autoconf libncurses5-dev elixir
           erlang-base erlang-public-key erlang-asn1 erlang-ssl
           erlang-dev erlang-inets erlang-eunit erlang-common-test
           rebar3 iputils-ping

    - name: Clone and build tpnode
      run: |
        git clone -b ${GITHUB_REF##*/} https://github.com/${{github.repository}}.git
        cd tpnode
        rebar3 compile
        rebar3 release
        rebar3 tar

